#!/usr/bin/env ansible-playbook
# Execute this playbook as `./playbook.yml`

- hosts: localhost
  connection: local
  become: yes
  vars_files:
    - vars.yml
  roles:
    - role: common
      tags: common