---
- name: Enable fstrim
  ansible.builtin.systemd:
    name: fstrim.timer
    enabled: true
    state: started

- name: Enable Nested Virtualization
  ansible.builtin.copy:
    content: "options kvm_{{ cpu_brand }} nested=1"
    dest: /etc/modprobe.d/kvm_{{ cpu_brand }}.conf

- name: Enable optimized disk schedulers
  ansible.builtin.copy:
    src: 60-ioschedulers.rules
    dest: /etc/udev/rules.d/

- name: Hardware monitoring/diagnostic tools
  community.general.pacman:
    name:
      - dmidecode
      - dosfstools
      - exfatprogs
      - lm_sensors
      - ntfs-3g
      - nvme-cli
    state: present