---
- name: Get CPU vendor
  set_fact:
    cpu_brand: "{{ 'intel' if (ansible_facts['processor'] is search('GenuineIntel')) else 'amd' }}"

- import_tasks: network.yml

- import_tasks: localization.yml

- import_tasks: pacman.yml

- import_tasks: ntp.yml

- import_tasks: sudo.yml

- import_tasks: virtual.yml
  when: ansible_facts['virtualization_role'] == 'guest'

- import_tasks: baremetal.yml
  when: ansible_facts['virtualization_role'] == 'host'

- name: Disable beep
  ansible.builtin.copy:
    content: 'blacklist pcspkr'
    dest: /etc/modprobe.d/nobeep.conf

- name: Essential packages - base system
  community.general.pacman:
    name:
      - "{{ cpu_brand }}-ucode"
      - base-devel
      - bash-completion
      - btop
      - htop
      - jq
      - kernel-modules-hook
      - man
      - ncdu
      - neovim
      - p7zip
      - python-docker
      - rsync
      - tree
      - unrar
      - unzip
      - wget
      - zip
      - zstd
    state: present

- import_tasks: aur.yml