---
- name: Get CPU vendor
  set_fact:
    cpu_brand: "{{ 'intel' if (ansible_facts['processor'] is search('GenuineIntel')) else 'amd' }}"

- import_tasks: network.yml

- import_tasks: localization.yml

- import_tasks: pacman.yml

- import_tasks: ntp.yml

- import_tasks: virtual.yml
  when: ansible_facts['virtualization_role'] == 'guest'

- import_tasks: baremetal.yml
  when: ansible_facts['virtualization_role'] == 'host'

- import_tasks: refind.yml

- name: Disable beep
  ansible.builtin.copy:
    content: 'blacklist pcspkr'
    dest: /etc/modprobe.d/nobeep.conf

- name: Essential packages - base system
  community.general.pacman:
    name: "{{ essential_packages }}"
    state: present

# - import_tasks: users.yml

- import_tasks: aur.yml