---
- name: Enable Pacman QOL enhancements
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - { regexp: '^#Color$', replace: 'Color' }
    - { regexp: '^#VerbosePkgLists$', replace: 'VerbosePkgLists' }
    - { regexp: '^#ParallelDownloads = 5$', replace: 'ParallelDownloads = 10' }

- name: Update pacman cache
  community.general.pacman:
    update_cache: yes

- name: Install Arch package utilities
  community.general.pacman:
    name:
      - namcap
      - pacman-contrib
      - pkgfile
    state: present

- name: Add paccache hooks
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /etc/pacman.d/hooks/
  with_items:
    - files/99-paccache_remove.hook
    - files/99-paccache_upgrade.hook

- name: Enable pkgfile timer
  ansible.builtin.systemd:
    name: pkgfile-update.timer
    enabled: True
  when: not ansible_check_mode