---
- name: Essential packages - base system
  community.general.pacman:
    name:
      - "{{ cpu_brand }}-ucode"
      - base-devel
      - bash-completion
      - btop
      - docker
      - docker-compose
      - git
      - htop
      - jq
      - kernel-modules-hook
      - man
      - ncdu
      - neovim
      - p7zip
      - python-docker
      - rsync
      - tree
      - unrar
      - unzip
      - wget
      - zip
    state: present

- name: Essential packages - networking
  community.general.pacman:
    name:
      - bind-tools
      - inetutils
      - iperf3
      - iputils
      - nmap
      - speedtest-cli
      - tcpdump
      - traceroute
    state: present

- name: Enable docker service
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state:  started
  when: not ansible_check_mode
