---
- name: Essential packages - base system
  pacman:
    name:
      - "{{ cpu_brand }}-ucode"
      - base-devel
      - bash-completion
      - btop
      - cronie
      - htop
      - kernel-modules-hook
      - man
      - ncdu
      - neovim
      - p7zip
      - rsync
      - tree
      - unrar
      - unzip
      - wget
      - zip
    state: present

- name: Essential packages - hardware tools
  pacman:
    name:
      - dmidecode
      - dosfstools
      - exfatprogs
      - lm_sensors
      - ntfs-3g
      - nvme-cli
    state: present
  when: ansible_facts['virtualization_role'] == 'host'

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Remove iptables if installed
  pacman:
    name:
       - iptables
    force: yes
    state: absent
  when:
    - ansible_facts.packages['iptables'] is defined
    - ansible_facts.packages['iptables'] | length != 0

- name: Essential packages - networking
  pacman:
    name:
      - bind-tools
      - inetutils
      - iperf3
      - iptables-nft
      - iputils
      - nmap
      - speedtest-cli
      - tcpdump
      - traceroute
    state: present

- name: Essential packages - devops tools
  pacman:
    name:
      - docker
      - docker-compose
      - git
      - jq
      - python-docker

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes
    state:  started
  when: not ansible_check_mode

