---
- name: Create locale.gen
  ansible.builtin.template:
    src: locale.gen.j2
    dest: /etc/locale.gen

- name: Generate locales
  community.general.locale_gen:
    name: "{{ item | split(' ') | first }}"
    state: present
  with_items: "{{ locales }}"

- name: Configure languages
  ansible.builtin.copy:
    content: |
      LANG=en_US.UTF-8
      LC_NUMERIC=pt_BR.UTF-8
      LC_TIME=pt_BR.UTF-8
      LC_MONETARY=pt_BR.UTF-8
      LC_PAPER=pt_BR.UTF-8
      LC_MEASUREMENT=pt_BR.UTF-8
    dest: /etc/locale.conf