---
- name: Get CPU vendor
  set_fact:
    cpu_brand: "{{ 'intel' if (ansible_facts['processor'] is search('GenuineIntel')) else 'amd' }}"

- import_tasks: network.yml

- import_tasks: localization.yml

- import_tasks: pacman.yml

- import_tasks: ntp.yml

- import_tasks: virtual.yml
  when: ansible_facts['virtualization_role'] == 'guest'

- import_tasks: baremetal.yml
  when: ansible_facts['virtualization_role'] == 'host'

- import_tasks: aur.yml

- name: Disable beep
  community.general.kernel_blacklist:
    name: pcspkr
    state: present
  become: yes