---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname | default('arch') }}"
    use: systemd
  when: not ansible_check_mode

- name: Configure /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts

- name: Install networking stack
  community.general.pacman:
    name:
      - dhclient
      - dnsmasq
      - networkmanager
    state: present

- name: Disables systemd-networkd if enabled
  ansible.builtin.systemd:
    name: systemd-networkd
    enabled: no
    state:  stopped

- name: Configure NetworkManager to use dhclient and dnsmasq
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/NetworkManager/conf.d/
    owner: root
    group: root
    mode: '0644'
  with_items:
    - dhcp.conf
    - dns.conf
  notify:
    - Restart NetworkManager

- name: Add Polkit rule to manage network connections
  ansible.builtin.copy:
    src: 50-org.freedesktop.NetworkManager.rules
    dest: /etc/polkit-1/rules.d/
    owner: root
    group: root
  notify:
    - Restart NetworkManager

- name: Enable NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: yes
    state:  started