---
- name: Set timezone
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link

- name: Copy systemd-timesyncd config
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf

- name: Enable systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    enabled: true
    state: started