---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname | default('arch') }}"
    use: systemd
  when: not ansible_check_mode

- name: Configure /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts